/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mim_mimer_sender_Sender */

#ifndef _Included_com_mim_mimer_sender_Sender
#define _Included_com_mim_mimer_sender_Sender
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mim_mimer_sender_Sender
 * Method:    Relate
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mim_mimer_sender_Sender_Relate
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_mim_mimer_sender_Sender
 * Method:    Login
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mim_mimer_sender_Sender_Login
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     com_mim_mimer_sender_Sender
 * Method:    Write
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mim_mimer_sender_Sender_Write
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_mim_mimer_sender_Sender
 * Method:    Read
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mim_mimer_sender_Sender_Read
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_mim_mimer_sender_Sender
 * Method:    cfinalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mim_mimer_sender_Sender_cfinalize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
