#ifndef ERRCODE_H
#define ERRCODE_H

/* CONNACK return code */
#define CONNACK_ACCEPTED 0x0
#define CONNACK_REFUSED_PROTOCOL_VERSION 0x1
#define CONNACK_REFUSED_IDENTIFIER_REJECTED 0x2
#define CONNACK_REFUSED_SERVER_UNAVAILABLE 0x3
#define CONNACK_REFUSED_BAD_USERNAME_PASSWORD 0x4
#define CONNACK_REFUSED_NOT_AUTHORIZED 0x5

#define PACKET_ENCODE_OK     200
#define NO_SUPPORT_RESP      400
#define NO_SUPPORT_REQ       404
#define PACKET_ENCODE_ERROR  500
#define PACKET_DECODE_ERROR  501
/* publish max payload size */
#define MQTT_MAX_PAYLOAD 268435455

/* PINGREQ client status flag */
#define PING_WRITING  0x1
#define PING_BUSYNESS 0x2

#endif // ERRCODE_H
